import numpy as np
import configparser
import bilby

"""distinguish capital and small"""
class MyConfigParser(configparser.ConfigParser):
    def optionxform(self, optionstr):
        return optionstr

file_number = 100

# A1_sample = bilby.core.prior.Uniform(0, 100).sample(file_number)
# A2_sample = bilby.core.prior.Uniform(0, 100).sample(file_number)

# A_sample = bilby.core.prior.LogUniform(1e-2, 1e2).sample(file_number)
A_sample = bilby.core.prior.Uniform(0, 100).sample(file_number)
alpha_sample = bilby.core.prior.Uniform(-1, 0).sample(file_number)

f1_sample = bilby.core.prior.Uniform(20, 500).sample(file_number)
f2_sample = bilby.core.prior.Uniform(20, 500).sample(file_number)
tau1_sample = bilby.core.prior.Uniform(-0.05, -0.001).sample(file_number)
tau2_sample = bilby.core.prior.Uniform(-0.05, -0.001).sample(file_number)
phi1_sample = bilby.core.prior.Uniform(-np.pi, np.pi, boundary='periodic').sample(file_number)
phi2_sample = bilby.core.prior.Uniform(-np.pi, np.pi, boundary='periodic').sample(file_number)

# ra_sample = bilby.core.prior.Uniform(0, 2 * np.pi, boundary='periodic').sample(file_number)
# dec_sample = bilby.core.prior.Cosine(boundary='reflective').sample(file_number)
# psi_sample = bilby.core.prior.Uniform(0, np.pi, boundary='periodic').sample(file_number)
# geocent_time_sample = bilby.core.prior.Uniform(-0.25, 0.25).sample(file_number)
ra_sample = np.zeros(file_number)
dec_sample = np.zeros(file_number)
psi_sample = np.zeros(file_number)
geocent_time_sample = np.zeros(file_number)

name = 'pp_two_mode_generated_by_OTparam_corrected'
for index in range(file_number):
    config = configparser.ConfigParser()
    config_path = './config/{}/{}_{}.ini'.format(name, name, index)

    """set [setting] section"""
    config['setting'] = {}
    setting = config['setting']
    setting['outdir_path'] = 'outdirs/{}/'.format(name)
    setting['event_name'] = '{}_{}'.format(name, index)
    setting['comment'] = 'two damped sinusoids for pp plot, generated by OTparam, correct injection range for A'
    setting['mode_number'] = 'two_mode'
    setting['analysis_mode_number'] = 'analysis_two_mode'

    """set [injection_parameters] section"""
    config['injection_parameters'] = {}
    injection_parameters = config['injection_parameters']

    injection_parameters['A'] = f'{A_sample[index]}'
    injection_parameters['alpha'] = f'{alpha_sample[index]}'
    
    # injection_parameters['A1'] = f'{A1_sample[index]}'
    # injection_parameters['A2'] = f'{A2_sample[index]}'
    
    injection_parameters['f1'] = f'{f1_sample[index]}'
    injection_parameters['f2'] = f'{f2_sample[index]}'
    injection_parameters['tau1'] = f'{tau1_sample[index]}'
    injection_parameters['tau2'] = f'{tau2_sample[index]}'
    injection_parameters['phi1'] = f'{phi1_sample[index]}'
    injection_parameters['phi2'] = f'{phi2_sample[index]}'
    
    injection_parameters['ra'] = f'{ra_sample[index]}'
    injection_parameters['dec'] = f'{dec_sample[index]}'
    injection_parameters['psi'] = f'{psi_sample[index]}'
    injection_parameters['geocent_time'] = f'{geocent_time_sample[index]}'

    """set [waveform_arguments] section"""
    config['waveform_arguments'] = {}
    waveform_arguments = config['waveform_arguments']
    waveform_arguments['reference_frequency'] = '{}'.format(50)
    waveform_arguments['minimum_frequency'] = '{}'.format(20)
    waveform_arguments['maximum_frequency'] = '{}'.format(512)

    """set [other_parameters] section"""
    config['other_parameters'] = {}
    other_parameters = config['other_parameters']
    other_parameters['duration'] = '{}'.format(0.5)
    other_parameters['sampling_frequency'] = '{}'.format(4096.0)
    other_parameters['post_trigger_duration'] = '{}'.format(0.25)

    """set [fix_parameters] section"""
    config['fix_parameters'] = {}
    config['fix_parameters']['fix_list'] = '["ra", "dec", "psi", "geocent_time"]'

    """write down in config file"""
    with open (config_path, mode = 'w') as f:
        config.write(f)

