[setting]
event_name = test_full
comment = test, parameters are set to be like pyRing example code
mode_number = two_mode

[injection_parameters]
A1_real = 1000
A1_imag = 1000
alpha_real = 0.1
alpha_imag = 0.1
w1_real = 1500
w1_imag = -200
w2_real = 1501
w2_imag = -200.1
ra = 0
dec = 0
psi = 0
geocent_time = 0

[waveform_arguments]
reference_frequency = 50
minimum_frequency = 20
maximum_frequency = 512

[other_parameters]
duration = 0.5
sampling_frequency = 4096.0
post_trigger_duration = 0.25

[fix_parameters]
fix_list = ["ra", "dec", "psi", "geocent_time"]
#fix_list = ["ra", "dec", "psi", "geocent_time", "A1_real", "A1_imag"]
#fix_list = ["ra", "dec", "psi", "geocent_time", "alpha_real", "alpha_imag", "w1_real", "w1_imag", "w2_real", "w2_imag"]
