[setting]
outdir_path = outdirs/
event_name = oneDS
comment = single mode injection and analysis with DS_Mirror parameterization
mode_number = one_mode
analysis_mode_number = analysis_one_mode
parameterization = DS_Mirror

[injection_parameters]
; A = 371
A = 96.3
alpha = 0.00029552945685847607
f1 = 201.23779332666524
tau1 = 0.0033219623034593474
f2 = 201.23779332666524
tau2 = 0.0023201731795771175
phi1 = 0
phi2 = 0
ra = 0
dec = 0
psi = 0
geocent_time = 0

[waveform_arguments]
minimum_frequency = 20
maximum_frequency = 512

[other_parameters]
duration = 0.5
sampling_frequency = 4096.0
post_trigger_duration = 0.25

[fix_parameters]
fix_list = ["ra", "dec", "psi", "geocent_time"]
; fix_list = ["ra", "dec", "psi", "geocent_time", "phi1", "phi2"]
; fix_list = ["ra", "dec", "psi", "geocent_time", "f1", "f2"]